package com.pbogdev.data


import com.pbogdev.data.network.dto.BeaconDto
import com.pbogdev.domain.models.Beacon
import com.pbogdev.domain.models.CustomResult
import com.pbogdev.domain.models.Profile
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue


class BeaconEncryptionCycleTest {

    private val cryptoEngine: CryptographyEngine = CryptographyEngineImpl()

    private val originalDomainBeacon = Beacon(
        beaconId = "beacon_abc123",
        profile = Profile(
            id = "user_998877",
            likes = "techno, late night drives",
            dislikes = "traffic",
            likesVector = floatArrayOf(0.85f, -0.22f),
            dislikesVector = floatArrayOf(-0.95f, 0.10f)
        ),
        vibeVector = floatArrayOf(0.77f, -0.11f),
        timestamp = 1710080000L
    )

    private val geohash = "sr2ym"
    private val timeWindow = "2026-03-10-UTC"

    // ==========================================
    // TEST 1: The Mapping Layer
    // ==========================================
    @Test
    fun `domain model maps to DTO and back without data loss`() {
        // Act
        val dto = originalDomainBeacon.toBeaconDto()
        val reconstructedDomain = dto.toBeacon()

        // Assert
        assertEquals(
            expected = originalDomainBeacon,
            actual = reconstructedDomain,
            message = "Mapping Layer failed: Data was lost or altered during DTO conversion"
        )
    }

    // ==========================================
    // TEST 2: The Serialization Layer
    // ==========================================
    @Test
    fun `DTO serializes to JSON and parses back correctly`() {
        // Arrange
        val originalDto = originalDomainBeacon.toBeaconDto()

        // Act
        val jsonString = Json.encodeToString(originalDto)

        // Quick sanity check to ensure our @SerialName annotations are actually working
        assertTrue(jsonString.contains("beacon_id"), "JSON should use @SerialName format")
        assertTrue(jsonString.contains("vibe_vector"), "JSON should use @SerialName format")

        val parsedDto = Json.decodeFromString<BeaconDto>(jsonString)

        // Assert - DTOs automatically get a proper equals() generated by Kotlin
        assertEquals(
            expected = originalDto,
            actual = parsedDto,
            message = "Serialization Layer failed: JSON parsing corrupted the DTO"
        )
    }

    // ==========================================
    // TEST 3: The Full Integration Pipeline
    // ==========================================
    @Test
    fun `full pipeline survives mapping serialization and encryption`() = runTest {
        // Act - OUTBOUND
        val dtoOut = originalDomainBeacon.toBeaconDto()
        val jsonString = Json.encodeToString(dtoOut)
        val encryptedBase64 = (cryptoEngine.encrypt(jsonString, geohash, timeWindow) as CustomResult.Success).data

        // Act - INBOUND
        val decryptedJsonString = (cryptoEngine.decrypt(encryptedBase64, geohash, timeWindow) as CustomResult.Success).data
        val dtoIn = Json.decodeFromString<BeaconDto>(decryptedJsonString)
        val reconstructedDomain = dtoIn.toBeacon()

        // Assert
        assertEquals(
            expected = originalDomainBeacon,
            actual = reconstructedDomain,
            message = "Integration Layer failed: The end-to-end pipeline broke the data"
        )
    }
}